"""Criação inicial das tabelas - versão final

Revision ID: 0b2cbf484f40
Revises: merge_suplementos_instrucao_uso
Create Date: 2025-07-19 10:54:41.305741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2cbf484f40'
down_revision = 'merge_suplementos_instrucao_uso'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suplementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('objetivo', sa.String(length=30), nullable=True),
    sa.Column('link_loja', sa.String(length=255), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('usuarios')
    op.drop_table('alimentos')
    op.drop_table('diarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('data_entrada', sa.DATE(), nullable=False),
    sa.Column('alimento_id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alimentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('calorias', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('proteinas', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('carboidratos', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('gorduras', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_usuario', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.drop_table('suplementos')
    # ### end Alembic commands ###
