"""Versão inicial completa do banco de dados

Revision ID: 6280d7d2a288
Revises: 
Create Date: 2025-07-19 11:37:45.588023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6280d7d2a288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('alimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('calorias', sa.Float(), nullable=True),
    sa.Column('proteinas', sa.Float(), nullable=True),
    sa.Column('carboidratos', sa.Float(), nullable=True),
    sa.Column('gorduras', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('preferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_refeicao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suplementos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('objetivo', sa.String(length=30), nullable=True),
    sa.Column('link_loja', sa.String(length=255), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('nivel_atividade', sa.String(length=50), nullable=True),
    sa.Column('objetivo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alergia_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('alergia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alergia_id'], ['alergia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfis_nutricionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('nivel_atividade', sa.String(length=30), nullable=True),
    sa.Column('objetivo', sa.String(length=30), nullable=True),
    sa.Column('aceita_suplementos', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plano_sugestao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_sugestao', sa.Date(), nullable=False),
    sa.Column('cafe_manha_receita_id', sa.Integer(), nullable=True),
    sa.Column('almoco_receita_id', sa.Integer(), nullable=True),
    sa.Column('jantar_receita_id', sa.Integer(), nullable=True),
    sa.Column('lanche_receita_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['almoco_receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['cafe_manha_receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['jantar_receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['lanche_receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferencia_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('preferencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['preferencia_id'], ['preferencia.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receita_alimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_gramas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimento.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_alimentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo_refeicao', sa.String(length=50), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=True),
    sa.Column('receita_id', sa.Integer(), nullable=True),
    sa.Column('quantidade_gramas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimento.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receita.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_alimentar')
    op.drop_table('receita_alimento')
    op.drop_table('preferencia_usuario')
    op.drop_table('plano_sugestao')
    op.drop_table('perfis_nutricionais')
    op.drop_table('alergia_usuario')
    op.drop_table('usuario')
    op.drop_table('suplementos')
    op.drop_table('receita')
    op.drop_table('preferencia')
    op.drop_table('alimento')
    op.drop_table('alergia')
    # ### end Alembic commands ###
